# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.0.3

jobs:
  build:
    executor: node/default # use the default executor defined within the orb
    working_directory: ~/project/repo-collector
    steps:
      - checkout:
          path:  ~/repo-collector
      - node/install-packages:
          pkg-manager: npm
      - node/test:
          
      - run:
          command: npm test
          name: Run tests
     # - persist_to_workspace:
     #     root: "~/project"
     #     paths:
     #       - .
