name: Upload Test Results To Codecov
on:
  pull_request:
  push:
    branches:
       - master
jobs:
  create-test-coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: repo-collector # set working directory within repo
    steps:
      - name: access repo
        uses: actions/checkout@master

      - name: set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.5.0'

      - name: install dependencies
        run: npm install

      - name: create coverage
        run: npm test -- --coverage .

      - name: upload to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./repo-collector/coverage
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
