name: Upload Test Results To Codecov
on:
  pull_request:
  push:
    # branches:
    #   - master
jobs:
  create-test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: access repo
        uses: actions/checkout@master

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.5.0'
          working-directory: ./repo-collector # react project is located within this directory, important for npm install and test

      - name: install dependencies
        run: npm install

      - name: create coverage
        run: npm test -- --coverage .

      - name: upload to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./repo-collector/coverage
          # files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
