name: Upload Test Results To Codecov
on: [push, pull_request]
jobs:
  create-test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: access repo
        uses: actions/checkout@master

      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.5.0'

      - name: create coverage
        run: npm test -- --coverage .

      - name: upload to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./repo-collector/coverage
          # files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
